apiVersion: apps/v1
kind: Deployment
metadata:
  name: finconecta-bot-deployment
  labels:
    app: finconecta-bot
spec:
  replicas: 3  # Puedes cambiar este número según el número de réplicas que necesites
  selector:
    matchLabels:
      app: finconecta-bot
  template:
    metadata:
      labels:
        app: finconecta-bot
    spec:
      containers:
      - name: finconecta-bot
        image: codelogman/finconecta_bot:latest  # Usa el nombre de tu imagen Docker
        ports:
        - containerPort: 8080  # Puedes cambiar este puerto según el que estés usando
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: finconecta-bot-service
spec:
  selector:
    app: finconecta-bot
  ports:
    - protocol: TCP
      port: 8080  # El puerto que expondrá el servicio
      targetPort: 8080  # El puerto donde el contenedor está escuchando
  type: LoadBalancer  # Esto permite que el servicio sea accesible desde fuera de Kubernetes

